### ISSUE TITLE
Engineer's Planner

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#11]
[old post](https://trello.com/c/xleEZhU1)
ItemId: `engineersplanner`

You need one of the structure’s blueprint to unlock in the planner.

- Once you’ve unlocked it, it will charge up, 60 seconds per charge. Each structure has their own max charges.
- When placing, it will place a blueprint structure, these can be removed to regain a charge by clicking on it.
- Interacting with it will build the structure, if you have to required materials.

---

- Just added a space check for when a plan has structure already occupying the space. 
- Unlocking a blueprint now grants you a charge to begin with.
- Plans now show build cost and requirements.

**Comment by Leroy8888** [comment]
Managed to find a few minor issues.

When you place down 2 different blueprint structures and hover over both of them it will very often display the cost of thestructure you hovered over prior. It also usually corrects itself after a few seconds, but only when you take the cursor off the blueprint structure (Example in image).
![Schermopname (11535)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/8764c34b-089f-4a9b-8eec-8f49bbc79a0f)

The structures can also be destroyed. However, when the wooden or metal fence get destroyed they remain for a longer period of time before they despawn. Their effects also still work when they get ''destroyed'' until the structures despawn.

**Comment by MXKhronos** [comment]
- Fixed the interactable tooltip to update when pointing at another plan.
- Fixed destroyed fences not breaking apart and despawning visual model after 60s.
- Despawning after 5 minutes in overworld is intended for any structures, there is no despawn timer for them in gamemodes.
- `barbedmetal` takes 15 dmg per zombie damaged with max health of 10'000.
- `barbedwooden` takes 30 dmg per enemy damaged with max health of 10'000.

So `barbedmetal` is twice as durable as `barbedwooden`.

**Comment by Leroy8888** [comment]
The issue with the structures despawn rather quickly still persists. They despawn well before they hit the 5 minute mark and it occurs when zombies get killed or when their ragdolls despawn. 

It can occur right after a structure got placed. This seems to be an issue in common with #37 .

**Comment by MXKhronos** [comment]
Figured out this long standing bug, thanks for the clues provided. 
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/38783502/2f908b32-ecf3-474e-b434-e6ba4cba5f6f)

- Replaced most `game.Debris:AddItem(...)` with my own custom delayed destroy method.

This should also theoretically fix the instantly despawning crates that's been an issue.
