### ISSUE TITLE
Tire Armor

### ISSUE THREAD

**Issue by MXKhronos** [HelixNebulaStudio/RiseOfTheDead#16]
ItemId: `tirearmor`
Description: Tire armor, made with tires. <b>Passive:</b> When equipping a melee, grants a 60% chance to block 20 damage from melee attacks. Reduced minimum damage is capped at 1 damage.

- Melee attacks are mostly zombie basic attacks.

**Comment by Leroy8888** [comment]
Doesn't seem to work yet. Cannot be modified or viewed in the workbench and its effect also does not seem to trigger when worn.

**Comment by MXKhronos** [comment]
Added missing workbench data for `tirearmor`. Also added a status to show TireArmor passive is active when a melee weapon is equipped.

**Comment by Leroy8888** [comment]
Maybe there could also be a little sound effect when the passive triggers

**Comment by MXKhronos** [comment]
Fixed melee weapons not triggering tire armor and added a sound for when the passive triggers.
https://github.com/HelixNebulaStudio/RiseOfTheDead/commit/dfb6ca533d0b22775b5875ec465c13aea729ef58

**Comment by Leroy8888** [comment]
The armor currently provides full immunity when worn against all melee attacks, which also remains after unequiping the armor. It also grants the passive whenever equiped, even if no melee weapon is held. This only changes upon leaving the server with the armor piece unequiped

Whenever a melee NPC besides a zombie attacks the player, while also wearing the armor the following warning pops up;
![Schermopname (11688)](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/162458509/e97bdf6a-6e8a-4bd2-a82c-02c4f6caa81d)

The sound it makes cannot actually be tested yet, since when worn melee enemy stop dealing **any** damage.

**Comment by JakobCh** [comment]
Effect seems to stay after you unequip the armor while wielding a melee weapon
![image](https://github.com/HelixNebulaStudio/RiseOfTheDead/assets/21036789/b149a314-a823-4f53-a79d-27276968a7aa)

**Comment by JakobCh** [comment]
You can re-equip the weapon on the new armor and you still get the tire armor buff again.

**Comment by MXKhronos** [comment]
Fixed

**Comment by Leroy8888** [comment]
It is a minor issue, but the passive still shows up when as a status when you equip the armor. Doesn't work but it does so regardless if you hold anything.

**Comment by MXKhronos** [comment]
> It is a minor issue, but the passive still shows up as a status when you equip the armor. Doesn't actually work but it does so regardless if you hold anything.

I can't seem to replicate this.

**Comment by JakobCh** [comment]
The passive icon seems to show up without you holding a melee weapon the first time you equip the armor after you join the game/a new server.
Doesn't happen if you have the armor equipped while you switch servers.
